name: Minstra
favicon: null
layout_spectrum: 0.75248
typography_spectrum: 0.43506
title: Minstra
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ded8e4'
    - '#1d1d1d'
    - '#334245'
    - '#7ca2b5'
    - '#67848a'
  brandStrength: 0
  lightness: 0.125
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
