name: Minstra
favicon: null
layout_spectrum: 0.8128030288498849
typography_spectrum: 0.6806872223969549
title: Minstra
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8717695917002857
  lightness: 0.11268345755524933
  saturation: 0.6961425780318677
  rhythmicContrast: 0.371640604455024
purpose: []
