name: Minstra
favicon: null
layout_spectrum: 0
typography_spectrum: 0.6806872223969549
title: Minstra
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ded8e4'
    - '#1d1d1d'
    - '#334245'
    - '#7ca2b5'
    - '#67848a'
  brandStrength: 0.5
  lightness: 0.11268345755524933
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
